# Generated by Django 4.0 on 2022-01-01 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='user1Choice',
            field=models.CharField(blank=True, choices=[('rock', 'rock'), ('paper', 'paper'), ('scissor', 'scissor')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='user2Choice',
            field=models.CharField(blank=True, choices=[('rock', 'rock'), ('paper', 'paper'), ('scissor', 'scissor')], max_length=10, null=True),
        ),
    ]
